#!/usr/bin/env python

import sys
import os

dmenu_recent_path = os.path.join(os.environ['HOME'], '.dmenu_recent')

if sys.argv[1] == '-s':
    cmd = sys.stdin.readline()
    with open(dmenu_recent_path, 'a+') as f:
        f.write(cmd)
    sys.stdout.write(cmd)
elif sys.argv[1] == '-r':
    lines = open(dmenu_recent_path).readlines()[::-1]
    commands = set()

    for cmd in lines:
        if cmd not in commands and cmd != '\n':
            sys.stdout.write(cmd)
            commands.add(cmd)

